import type { NextPage } from 'next';
import React, { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import SearchAppBar from '../../components/SearchBar';
import { Grid, Skeleton } from '@mui/material';
import { styled, alpha } from '@mui/material/styles';
import styles from '../styles/Query.module.css';
import { useRouter } from 'next/router';
import SearchResult from '../../components/reusable/SearchResult';

const Query: NextPage = () => {

  const Item = styled('div')(({ theme }) => ({
    ...theme.typography.body2,
    // padding: theme.spacing(1),
    // textAlign: 'center',
    color: theme.palette.text.secondary,
  }));

  const { query } = useRouter();
  console.log(query.queryString);

  var [loading, setLoading] = useState(false);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchAppBar/>
      {loading === false ?
      <Grid container spacing={1} direction="column">
        <Grid item xs={12}>
          <Skeleton variant="text" animation="wave" height={30} width="25%" onClick={() => {
            setLoading(!loading);
          }}/>
        </Grid>
        <Grid item xs={12}>
          <Skeleton variant="rectangular" height={150} animation="wave"/>
        </Grid>
        <Grid item xs={12}>
          <Skeleton variant="rectangular" height={150} animation="wave"/>
        </Grid>
        <Grid item xs={12}>
          <Skeleton variant="rectangular" height={150} animation="wave"/>
        </Grid>
      </Grid>
      :
      <Grid container spacing={1} direction="column">
        <Grid item xs={12}>
          <Item onClick={() => {
            setLoading(!loading);
          }}
          >Showing 3 of 3 items</Item>
        </Grid>
        <Grid item xs={12}>
          <SearchResult/>
        </Grid>
        <Grid item xs={12}>
          <SearchResult/>
        </Grid>
        <Grid item xs={12}>
          <SearchResult/>
        </Grid>
      </Grid>
      }
    </div>
  )
};

export default Query;
