import type { NextPage } from 'next';
import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import SearchAppBar from '../../components/SearchBar';
import { Grid, Skeleton } from '@mui/material';
import { styled, alpha } from '@mui/material/styles';
import { useRouter } from 'next/router';
import SearchResult from '../../components/queryPage/SearchResult';
import FilterSelect from '../../components/queryPage/FilterSelect';
import SortSelect from '../../components/queryPage/SortSelect';

const Query: NextPage = () => {

  const Item = styled('div')(({ theme }) => ({
    ...theme.typography.body2,
    // padding: theme.spacing(1),
    // textAlign: 'center',
    color: theme.palette.text.secondary,
  }));

  const userProp = {
    userId: 1,
    liked: false, //liked by current user
  }
  const songProp = {
    songName: 'Song Name',
    artistName: 'Artist Name',
    songPath: 'https://www2.cs.uic.edu/~i101/SoundFiles/BabyElephantWalk60.wav',
    genre: 'Rock',
    tags: ['smooth', 'funky'],
    artistPic: "https://artscimedia.case.edu/wp-content/uploads/sites/79/2016/12/14205134/no-user-image.gif",
    cumulativeLikes: 234,
  }
  const ProfileImage = () => {
    return (
      <Image src={songProp.artistPic} alt="artist-profile-picture" layout={"fixed"} width="75px" height="75px"/>
    )
  }

  const { query } = useRouter();
  console.log(query.queryString);

  var [loading, setLoading] = useState(false);



  return (
    <div>
      <Head>
        <title>improvibe</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchAppBar/>
      <Grid container spacing={1}>
          <Grid item xs={6}>
            <FilterSelect/>
          </Grid>
          <Grid item xs={6}>
            <SortSelect/>
          </Grid>
        </Grid>
      {loading === false ?
      <Grid container spacing={1} direction="column">
        <Grid item xs={12}>
          <Skeleton variant="text" animation="wave" height={30} width="25%" onClick={() => {
            setLoading(!loading);
          }}/>
        </Grid>
        <Grid item xs={12}>
          <Skeleton variant="rectangular" height={150} animation="wave"/>
        </Grid>
        <Grid item xs={12}>
          <Skeleton variant="rectangular" height={150} animation="wave"/>
        </Grid>
        <Grid item xs={12}>
          <Skeleton variant="rectangular" height={150} animation="wave"/>
        </Grid>
      </Grid>
      :
      <Grid container spacing={1} direction="column">
        <Grid item xs={12}>
          <Item onClick={() => {
            setLoading(!loading);
          }}
          >Showing 3 of 3 items</Item>
        </Grid>
        <Grid item xs={12}>
          <SearchResult song={songProp} user={userProp}/>
        </Grid>
        <Grid item xs={12}>
          <SearchResult song={songProp} user={userProp}/>
        </Grid>
        <Grid item xs={12}>
          <SearchResult song={songProp} user={userProp}/>
        </Grid>
      </Grid>
      }
    </div>
  )
};

export default Query;
