version: "3"
services:
  improvibe:
    image: happyboxes/improvibe
    ports:
      - 3000:3000
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock